export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Contient", value: "iLike" as const },
    { label: "Ne contient pas", value: "notILike" as const },
    { label: "Égal à", value: "eq" as const },
    { label: "Différent de", value: "ne" as const },
    { label: "Est vide", value: "isEmpty" as const },
    { label: "N'est pas vide", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Égal à", value: "eq" as const },
    { label: "Différent de", value: "ne" as const },
    { label: "Inférieur à", value: "lt" as const },
    { label: "Inférieur ou égal à", value: "lte" as const },
    { label: "Supérieur à", value: "gt" as const },
    { label: "Supérieur ou égal à", value: "gte" as const },
    { label: "Est entre", value: "isBetween" as const },
    { label: "Est vide", value: "isEmpty" as const },
    { label: "N'est pas vide", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Égal à", value: "eq" as const },
    { label: "Différent de", value: "ne" as const },
    { label: "Avant", value: "lt" as const },
    { label: "Après", value: "gt" as const },
    { label: "Le ou avant", value: "lte" as const },
    { label: "Le ou après", value: "gte" as const },
    { label: "Est entre", value: "isBetween" as const },
    { label: "Relatif à aujourd'hui", value: "isRelativeToToday" as const },
    { label: "Est vide", value: "isEmpty" as const },
    { label: "N'est pas vide", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "Égal à", value: "eq" as const },
    { label: "Différent de", value: "ne" as const },
    { label: "Est vide", value: "isEmpty" as const },
    { label: "N'est pas vide", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Contient au moins un de", value: "inArray" as const },
    { label: "Ne contient aucun de", value: "notInArray" as const },
    { label: "Est vide", value: "isEmpty" as const },
    { label: "N'est pas vide", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "Égal à", value: "eq" as const },
    { label: "Différent de", value: "ne" as const },
  ],
  sortOrders: [
    { label: "Ascendant", value: "asc" as const },
    { label: "Descendant", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};